name: Build package-list

on:
  workflow_dispatch:

jobs:
  build-pkgs:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@build_list
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
        
######### EDIT:
          package_list: plasma
          release_tag: 5.27.0-LTS
          ## path to source repo
          source_url: https://github.com/2091527886/plasma-5.25-lts-PKGBUILDs.git
          source_folder: plasma-5.25-lts-PKGBUILDs
          ## branch: (default: stable)
          branch: stable
          ## custom-repo - default: ""
          custom-repo: ""
