name: Build package-list

on:
  push:
  workflow_dispatch:

jobs:
  build-pkg:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro/manjaro-pkg-action@build_list
        with:
          gpg-key: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
        
######### EDIT:
          package_list: plasma
          release_tag: 5.24.7
          repo: community
          ## path to source repo
          source: https://github.com/manjaro/plasma-5.24-lts-PKGBUILDs.git
          ## branch: (default: stable)
          branch: stable
          ## custom-repo - default: ""
          custom-repo: ""
